/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LeavingRouteImport } from './routes/leaving'
import { Route as HomeRouteImport } from './routes/home'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileEditRouteImport } from './routes/profile.edit'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LeavingRoute = LeavingRouteImport.update({
  id: '/leaving',
  path: '/leaving',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileEditRoute = ProfileEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ProfileRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/home': typeof HomeRoute
  '/leaving': typeof LeavingRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/rewards': typeof RewardsRoute
  '/search': typeof SearchRoute
  '/profile/edit': typeof ProfileEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/home': typeof HomeRoute
  '/leaving': typeof LeavingRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/rewards': typeof RewardsRoute
  '/search': typeof SearchRoute
  '/profile/edit': typeof ProfileEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/home': typeof HomeRoute
  '/leaving': typeof LeavingRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/rewards': typeof RewardsRoute
  '/search': typeof SearchRoute
  '/profile/edit': typeof ProfileEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/home'
    | '/leaving'
    | '/notifications'
    | '/profile'
    | '/reset-password'
    | '/rewards'
    | '/search'
    | '/profile/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/home'
    | '/leaving'
    | '/notifications'
    | '/profile'
    | '/reset-password'
    | '/rewards'
    | '/search'
    | '/profile/edit'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/home'
    | '/leaving'
    | '/notifications'
    | '/profile'
    | '/reset-password'
    | '/rewards'
    | '/search'
    | '/profile/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  HomeRoute: typeof HomeRoute
  LeavingRoute: typeof LeavingRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  RewardsRoute: typeof RewardsRoute
  SearchRoute: typeof SearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaving': {
      id: '/leaving'
      path: '/leaving'
      fullPath: '/leaving'
      preLoaderRoute: typeof LeavingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/edit': {
      id: '/profile/edit'
      path: '/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof ProfileEditRouteImport
      parentRoute: typeof ProfileRoute
    }
  }
}

interface ProfileRouteChildren {
  ProfileEditRoute: typeof ProfileEditRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileEditRoute: ProfileEditRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  HomeRoute: HomeRoute,
  LeavingRoute: LeavingRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  RewardsRoute: RewardsRoute,
  SearchRoute: SearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
